[2025-05-06T10:51:25.952+0000] {scheduler_job_runner.py:843} ERROR - Executor reports task instance <TaskInstance: test_mysql_connection.query_mysql manual__2025-05-06T10:51:26.672296+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
