[2025-05-08T14:59:41.927+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-08T14:59:41.997+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl_decorator.load.load_dim_customers manual__2025-05-08T14:58:40.551626+00:00 [queued]>
[2025-05-08T14:59:42.029+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl_decorator.load.load_dim_customers manual__2025-05-08T14:58:40.551626+00:00 [queued]>
[2025-05-08T14:59:42.030+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-08T14:59:42.083+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load.load_dim_customers> on 2025-05-08 14:58:40.551626+00:00
[2025-05-08T14:59:42.101+0000] {standard_task_runner.py:63} INFO - Started process 10868 to run task
[2025-05-08T14:59:42.106+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl_decorator', 'load.load_dim_customers', 'manual__2025-05-08T14:58:40.551626+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_dw_dag.py', '--cfg-path', '/tmp/tmpj6cvl0e2']
[2025-05-08T14:59:42.111+0000] {standard_task_runner.py:91} INFO - Job 123: Subtask load.load_dim_customers
[2025-05-08T14:59:42.284+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl_decorator.load.load_dim_customers manual__2025-05-08T14:58:40.551626+00:00 [running]> on host ebff8b55cad8
[2025-05-08T14:59:42.503+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl_decorator' AIRFLOW_CTX_TASK_ID='load.load_dim_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T14:58:40.551626+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T14:58:40.551626+00:00'
[2025-05-08T14:59:42.506+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-08T14:59:42.513+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-08T14:59:42.514+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_to_warehouse.py", line 14, in load_to_warehouse
    raise FileNotFoundError(f"Did not find latest {table_name}.")
FileNotFoundError: Did not find latest dim_customers.
[2025-05-08T14:59:42.532+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl_decorator, task_id=load.load_dim_customers, run_id=manual__2025-05-08T14:58:40.551626+00:00, execution_date=20250508T145840, start_date=20250508T145942, end_date=20250508T145942
[2025-05-08T14:59:42.561+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 123 for task load.load_dim_customers (Did not find latest dim_customers.; 10868)
[2025-05-08T14:59:42.610+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-08T14:59:42.647+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-08T14:59:42.650+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
